### ISSUE TITLE
denied by branch protections

### ISSUE THREAD

**Issue by TomVasile** [gautamkrishnar/keepalive-workflow#12]
Wondering what is the best way to work around branch protections?

```
Error: {"command":"git push origin HEAD","exitCode":1,"outputData":"","errorData":"remote: error: GH006: Protected branch update failed for refs/heads/dev.        \nremote: error: At least 1 approving review is required by reviewers with write access. 2 of 2 required status checks are expected.
```

**Comment by gautamkrishnar** [comment]
@TomVasile simply add a `contents: write` to the yaml file:
```yaml
name: Github Action with a cronjob trigger
on:
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: write

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - step1
      # - step 2
      # - step n, use it as the last step
      - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
```
