### ISSUE TITLE
"unable to access" issue in multiple projects.

### ISSUE THREAD

**Issue by tyler36** [gautamkrishnar/keepalive-workflow#14]
Thank you for the creating this action. 
I have several open-source projects that use this action to test against an upstream stable/head builds.

About a week ago, I started recieving email notifications of tests failing: 

```json
{
    "command": "git push origin HEAD",
    "exitCode": 128,
    "outputData": "",
    "errorData": "remote: Permission to tyler[3](https://github.com/tyler36/ddev-tinker/actions/runs/5162752635/jobs/9315661265#step:12:3)6/ddev-tinker.git denied to github-actions[bot].\nfatal: unable to access 'https://github.com/tyler36/ddev-tinker.git/': The requested URL returned error: [4](https://github.com/tyler36/ddev-tinker/actions/runs/5162752635/jobs/9315661265#step:12:4)03\n"
}
```

```yml
with:
    gh_token: ***
    commit_message: Automated commit by Keepalive Workflow to keep the repository active
    committer_username: gkr-bot
    committer_email: gkr-bot@tuta.io
    time_elapsed: 50
    auto_push: true
  env:
    NIGHTLY_DDEV_PR_URL: https://nightly.link/ddev/ddev/actions/runs/1720215802/ddev-linux-amd64.zip
    DDEV_GITHUB_TOKEN: ***
    HOMEBREW_NO_INSTALL_FROM_API: 1
```

Link to [workflow.yml](https://github.com/tyler36/ddev-tinker/blob/42263b527bcdc08eeb31b7281e8c17c6b90a241f/.github/workflows/tests.yml#L1)
