### ISSUE TITLE
Use branch "keep-alive"

### ISSUE THREAD

**Issue by koppor** [gautamkrishnar/keepalive-workflow#18]
The action should not use the current main branch, but some other branch.

I know that with additional steps, this should be possible. Maybe, this should be documented in the README.md. Maybe, it is as simple as

```yaml
- run: git checkout -b keep-alive
```

**Comment by gautamkrishnar** [comment]
you may have branch protection enabled. It is not a common scenario though. You need to disable it https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule

**Comment by koppor** [comment]
I just want to keep the main branch clean. Independent of it being protected or not.

OK, I want it to protect from commits resulting of dumb GitHub decisions.

**Comment by bgctw** [comment]
The following should work with a branch other than main.
Although, I need to wait 50 days to see if the commit really works on the different branch. 

After creating branch `keepalive` in the [repo](https://github.com/bgctw/Bigleaf.jl), I added the following lines at the end of my `CompatHelper.yml` action:

```
- uses: actions/checkout@v2
        with:
          ref: 'keepalive'      # The branch, tag or SHA to checkout. 
- uses: gautamkrishnar/keepalive-workflow@v1
```
