### ISSUE TITLE
[Question] Write Permission check

### ISSUE THREAD

**Issue by julienloizelet** [gautamkrishnar/keepalive-workflow#20]
Hi,

First, thanks for this very useful action.

Then, a few remarks: 

since the release `1.2.0` (including [this commit](https://github.com/gautamkrishnar/keepalive-workflow/commit/d1915cefbcc65daec69e9255581798cb61b9dc3d) ), almost all my Keep Alive workflows no longer work because I protect the `main` branch on almost all my projects.

I guess I can solve it by setting `auto_write_check` to `false` (did no test yet, am I right ?).

Setting the default value of `auto_write_check` to `true` is a kind of breaking change for me, and I would have prefer a `@v2` maybe (or still a `@v1` if the default value is `false`).

Finally, my question is: 

Is it normal that, even if we set explicitly the write permission in the workflow, the Keep alive step will throw an error ?

For example, 

I'm using this generic action : 

```
name: Keep Alive
on:

 schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  keep-alive:

    name: Keep Alive
    runs-on: ubuntu-latest

    steps:

      - name: Clone project files
        uses: actions/checkout@v3

      # keepalive-workflow adds a dummy commit if there's no other action here, keeps
      # GitHub from turning off tests after 60 days
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: "chore(*): Automated commit to keep the repository active"
          time_elapsed: 55
```          
          
And it fails (because I protected the main branch) even if there is the `permissions:contents: write` directive.

Thanks
