### ISSUE TITLE
My workflow has been disabled even if I use this action

### ISSUE THREAD

**Issue by julienloizelet** [gautamkrishnar/keepalive-workflow#34]
Hi,

Am I doing something wrong or is this a bug ?

Every week, I run the v2 version of this action using a simple "Keep Alive" action: https://github.com/julienloizelet/ddev-tools/actions/workflows/keepalive.yml

I use it so that another "test" action is not disabled: 

https://github.com/julienloizelet/ddev-tools/actions/workflows/tests.yml

But, it has been disabled today: 

---

<img width="1320" alt="Screenshot 2024-05-14 at 16 36 32" src="https://github.com/gautamkrishnar/keepalive-workflow/assets/20956510/5ec02d42-b9f4-4b7a-8c42-5026bc649016">

---

I don't see any error in the Keep Alive workflow: 

---

<img width="800" alt="Screenshot 2024-05-14 at 16 39 28" src="https://github.com/gautamkrishnar/keepalive-workflow/assets/20956510/708e61c8-edc9-473a-8db1-f2d901e1f098">

---

But despite this, the "test" action has been deactivated. 

Do you have an idea of what could be the reason of this behavior ?

Thanks !

**Comment by julienloizelet** [comment]
I just found this release note: https://github.com/gautamkrishnar/keepalive-workflow/releases/tag/2.0.1
and I think I've found the cause of my problem.


As I started using this action with the dummy commit of v1, it was already working to have a separate "keep alive" workflow: all scheduled workflows were kept alive as a new commit was detected.

With the v2, if we use a separate "keep alive" workflow, we have to specify which workflow we want to keep active ?

Thanks

**Comment by gautamkrishnar** [comment]
@julienloizelet yes you are right. With v2 you need to add it to every individual workflows you want to keep alive. Or you can also simply use `workflow_files` to manually specify multiple workflows. 

Check the example https://github.com/gautamkrishnar/keepalive-workflow?tab=readme-ov-file#advanced-use-cases

```yaml
name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * *"
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: "build1.yml, build2.yml"
          time_elapsed: "0"
```
