### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by timotejroiko** [gautamkrishnar/keepalive-workflow#44]
i have a workflow that runs once per day and today i got this

![image](https://github.com/user-attachments/assets/526bc2a1-6816-4336-a25a-0f736866b61d)

here is my workflow file (there are no other workflows on the repo)

```yml
name: Compile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: actions/checkout@v4

      - name: lzip
        run: sudo apt install -y lzip

      - id: check
        name: check
        run: node build.js | tee out.txt; echo "RESULT=$(tail out.txt -n 1)" >> $GITHUB_OUTPUT; rm out.txt

      - name: commit
        if: steps.check.outputs.RESULT == 'Done'
        uses: stefanzweifel/git-auto-commit-action@v5

      - name: keepalive
        uses: gautamkrishnar/keepalive-workflow@v2
```

**Comment by gautamkrishnar** [comment]
@timotejroiko Please follow the example correctly: https://github.com/gautamkrishnar/keepalive-workflow?tab=readme-ov-file#how-to-use

you do not have required permissions set change:
```yaml
name: Compile
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write

```
to
```yaml
name: Compile
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
       actions: write
```
