### ISSUE TITLE
Error when using workflow

### ISSUE THREAD

**Issue by ronaldtse** [gautamkrishnar/keepalive-workflow#6]
We're trying to use this keepalive workflow in this public repository:
https://github.com/ietf-ribose/iana-registries-sync/

However, the step terminates with:
https://github.com/ietf-ribose/iana-registries-sync/runs/7194659165?check_suite_focus=true#step:11:10

<img width="921" alt="Screenshot 2022-07-05 at 7 41 26 PM" src="https://user-images.githubusercontent.com/11865/177310474-5cdd988d-4905-421d-8b46-32b2c19ddecd.png">

The relevant config is just this line:
https://github.com/ietf-ribose/iana-registries-sync/blob/389c5436b3ec408f6c3accd753ff41c0fc198e04/.github/workflows/import.yml#L73

Any idea? Thanks!

**Comment by gautamkrishnar** [comment]
@ronaldtse you are cloning a new repo into the folder `iana-registries` which is not exactly the folder that the blog post workflow is supposed to be executed on. Add checkout to switch back to the actual repository and then run the workflow.

**Comment by gautamkrishnar** [comment]
Please use the following and try:
```yaml
name: import

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '10 * * * *'  # every hour at *:10

jobs:
  import:
    name: import
    runs-on: ubuntu-latest
    # continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout iana-registries repo
        uses: actions/checkout@v2
        with:
          repository: ietf-ribose/iana-registries
          token: ${{ secrets.IETF_RIBOSE_CI_PAT }}
          path: iana-registries

      - name: Setup Git
        run: |
          git config --global user.name "ietf-ribose-ci"
          git config --global user.email "ietf-ribose-ci@users.noreply.github.com"

      - name: Add GitHub remote to repo
        working-directory: iana-registries
        run: |
          git remote set-url origin \
            https://${{ secrets.IETF_RIBOSE_CI_USERNAME }}:${{ secrets.IETF_RIBOSE_CI_PAT }}@github.com/ietf-ribose/iana-registries

      - name: Perform rsync from IANA
        working-directory: iana-registries
        run: |
          rsync -avciz --delete-before \
            --exclude '.git*' \
            --exclude 'README.*' \
            rsync.iana.org::assignments .

      - name: Git diff
        working-directory: iana-registries
        run: |
          git diff

      - name: Skip the rest if no changes
        id: git_status
        working-directory: iana-registries
        run: |
          echo ::set-output name=STATUS::$(git status --porcelain | tr -d [:space:])

      - name: Add changes
        if: steps.git_status.outputs.STATUS != ''
        working-directory: iana-registries
        run: |
          git add -A
          git commit -m "$(date -R -u)"

      - name: Git log
        if: steps.git_status.outputs.STATUS != ''
        working-directory: iana-registries
        run: |
          git log | head -100

      - name: Git push to GitHub iana-registries
        if: steps.git_status.outputs.STATUS != ''
        working-directory: iana-registries
        run: |
          git push --all -f
          git push --tags -f
      - name: Checkout
         uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@v1
        # with:
        #   committer_username: ietf-bib-bot
        #   committer_email: gh-bib-bot@llc.ietf.org
```
